### ISSUE TITLE
Issue compiling with dub

### ISSUE THREAD

**Issue by infinityplusb** [pineapplemachine/mach.d#1] opened 2016-09-15 07:05 UTC
Hello fair developer person

I created a new dub project using 
`dub init testmyplz`

then I cd'd into the source folder and clone mach.d 
`cd testmeplz\ && git clone https://github.com/pineapplemachine/mach.d.git`

then 
`cd .. && dub`

This found all of your source files, but I come up with a few errors.
It doesn't look like some of these are "Work In Progress" cause they haven't been updated in a while, so I was wondering if I was doing something wrong, or how you normally build this.

FYI I was looking at replicating your OpenGL example in 
`http://forum.dlang.org/post/reopecqdhrbakxhwcppo@forum.dlang.org`

```
source\mach.d\mach\range\chain\iterable.d(109,27): Error: function declaration without return type. (Note that constructors are always named 'this')                                                    
source\mach.d\mach\range\chain\iterable.d(109,43): Error: semicolon expected to close alias declaration                                                                                                 
source\mach.d\mach\range\chain\iterable.d(109,43): Error: found '=>' instead of statement                                                                                                               
source\mach.d\mach\range\chain\iterable.d(214,35): Error: basic type expected, not (                                                                                                                    
source\mach.d\mach\range\chain\iterable.d(214,35): Error: function declaration without return type. (Note that constructors are always named 'this')                                                    
source\mach.d\mach\range\chain\iterable.d(214,51): Error: semicolon expected to close alias declaration                                                                                                 
source\mach.d\mach\range\chain\iterable.d(214,51): Error: found '=>' instead of statement                                                                                                               
source\mach.d\mach\range\compare.d(27,36): Error: basic type expected, not (                                                                                                                            
dmd failed with exit code 1.                             
```

**Comment by pineapplemachine** [comment] 2016-09-15 09:21
Just confirmed that both `iterable.d` and `compare.d` compile and run unittests successfully with dmd 64-bit v2.071.2-b1 on OSX Mavericks, and a similar 32-bit version on Windows 7. (Can't recall the exact dmd version and haven't got the machine within reach.) Your compiler seems to be specifically having issues with lambda declarations such as this one: `alias lengthsum = (size_t len, r) => (len + r.length);` (line 109 of `range/chain/iterable.d`).

What version of dmd are you running? If it's an older version and it's practical for you to upgrade that should fix the problem, otherwise I'll look into better backwards-compatibility.

**Comment by infinityplusb** [comment] 2016-09-15 11:31
Ok, so I updated my dmd version

```
brian@brians-Hub:~/Documents/Programming/d/opengl$ dmd --version
DMD64 D Compiler v2.071.1
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
```

I needed to add 2 lines of dependencies:

```
dependency "derelict-gl3" version="~>1.0.19"
dependency "derelict-sdl2" version="~>2.0.1"
```

which led to an issue about `mach/sdl/texture.d`

```
brian@brians-Hub:~/Documents/Programming/d/opengl$ dub
Fetching derelict-sdl2 2.0.1 (getting selected version)...
Placing derelict-sdl2 2.0.1 to /home/brian/.dub/packages/...
Performing "debug" build using dmd for x86_64.
derelict-util 2.1.0: target for configuration "library" is up to date.
derelict-gl3 1.0.19: target for configuration "library" is up to date.
derelict-sdl2 2.0.1: building configuration "library"...
opengl ~master: building configuration "application"...
source/mach.d/mach/misc/refcounter.d(77,24): Warning: instead of C-style syntax, use D-style syntax 'T[] values'
source/mach.d/mach/misc/refcounter.d(81,36): Warning: instead of C-style syntax, use D-style syntax 'T[] values'
source/mach.d/mach/range/find/findelement.d(65,31): Warning: use '{ }' for an empty statement, not a ';'
source/mach.d/mach/sdl/input/controller.d(159,59): Warning: use '{ }' for an empty statement, not a ';'
source/mach.d/mach/sdl/input/joystick.d(212,53): Warning: use '{ }' for an empty statement, not a ';'
source/app.d(4,8): Error: module texture is in file 'mach/sdl/texture.d' which cannot be read
import path[0] = source/
import path[1] = ../../../../.dub/packages/derelict-gl3-1.0.19/derelict-gl3/source/
import path[2] = ../../../../.dub/packages/derelict-util-2.1.0/derelict-util/source/
import path[3] = ../../../../.dub/packages/derelict-sdl2-2.0.1/derelict-sdl2/source/
import path[4] = /usr/include/dmd/phobos
import path[5] = /usr/include/dmd/druntime/import
dmd failed with exit code 1.
```

so, I changed the imports to:

```
import mach.sdl.graphics.texture;
import mach.sdl.graphics.color;
import mach.sdl.graphics.primitives;
```

but then I get other errors about 

```
source/mach.d/mach/math/vector2.d(15,21): Error: template instance isTemplateOf!(T, Vector2) template 'isTemplateOf' is not defined
source/mach.d/mach/sdl/graphics/primitives.d(51,28): Error: template instance mach.math.vector2.isVector2!(Vector2!int) error instantiating
source/mach.d/mach/math/vector3.d(15,21): Error: template instance isTemplateOf!(T, Vector3) template 'isTemplateOf' is not defined
source/mach.d/mach/sdl/graphics/primitives.d(55,28): Error: template instance mach.math.vector3.isVector3!(Vector2!int) error instantiating
source/mach.d/mach/sdl/graphics/primitives.d(66,46): Error: template mach.sdl.graphics.primitives.glset cannot deduce function from argument types !()(Vector2!int), candidates are:
source/mach.d/mach/sdl/graphics/primitives.d(51,6):        mach.sdl.graphics.primitives.glset(V)(V vector) if (isVector2!V)
source/mach.d/mach/sdl/graphics/primitives.d(55,6):        mach.sdl.graphics.primitives.glset(V)(V vector) if (isVector3!V)
source/mach.d/mach/sdl/graphics/primitives.d(84,24): Error: template instance mach.sdl.graphics.primitives.primitives!(1u, ubyte, int) error instantiating
...
source/mach.d/mach/sdl/haptic/haptic.d(127,42): Error: function pointer SDL_HapticRunEffect (SDL_Haptic*, int, SDL_HapticEffect*) is not callable using argument types (SDL_Haptic*, int, uint)
source/mach.d/mach/sdl/input/event/queue.d(98,14): Error: variable mach.sdl.input.event.queue.EventQueue.getfilter.result type void is inferred from initializer (*SDL_GetEventFilter)(&get.filter, &get.data), and variables cannot be of type void
source/mach.d/mach/sdl/input/event/queue.d(98,41): Error: expression (*SDL_GetEventFilter)(&get.filter, &get.data) is void and has no value
source/mach.d/mach/range/split.d(157,27): Error: no [] operator overload for type ArrayRange!(const(string), ulong)
source/mach.d/mach/range/split.d(90,12): Error: template instance mach.range.split.SplitIterableRange!(ArrayRange!(const(string), ulong), MapSingularRange!(__lambda2, FilterRange!(__lambda2, EnumerationRange!(ulong, ArrayRange!(const(string), ulong)))), ulong, false, false) error instantiating
source/mach.d/mach/text/parse/ini/parse.d(53,32):        instantiated from here: split!(__lambda25, cast(SplitInclusionMode)0, ulong, const(string), char)
source/mach.d/mach/text/parse/ini/parse.d(53,38): Error: template mach.range.map.combined.map!(asarray).map cannot deduce function from argument types !()(SplitIterableRange!(ArrayRange!(const(string), ulong), MapSingularRange!(__lambda2, FilterRange!(__lambda2, EnumerationRange!(ulong, ArrayRange!(const(string), ulong)))), ulong, false, false)), candidates are:
source/mach.d/mach/range/map/combined.d(15,10):        mach.range.map.combined.map!(asarray).map(Iters...)(Iters iters) if (canMap!(transform, Iters))

```

I'll keep digging around

**Comment by pineapplemachine** [comment] 2016-09-15 11:57
The import errors you got were because some modules moved since I posted that example.

The first set of errors is caused by me forgetting to import something and everything still compiling the last time I tested for whatever dumb reason, my bad

The SDL-related errors are because the dub package for DerelictSDL2 is behind, point to the master branch of the Github repo instead. (Though now that I think of it even once you do that you'll run into a couple issues related to not-yet-merged PRs. Try grabbing the master branch of my forks? That _might_ work, for now.)

The errors originating from `mach.text.parse.ini` are because that's a WIP package and why is dub trying to build it anyway? Nothing is importing that. (Shit like this is why I don't use dub.)

**Comment by pineapplemachine** [comment] 2016-09-15 22:33
Ok, I went through and fixed the import errors, and until [this PR](https://github.com/DerelictOrg/DerelictSDL2/pull/55) goes through you should be able to rely on [this branch of this repo](https://github.com/pineapplemachine/DerelictSDL2) for the DerelictSDL2 dependency.

I'm not sure why dub attempted to compile the unfinished ini package, but I'm going to say that attempting it in the first place was an error on dub's part. Failing all else, you can just delete the folder containing that package.

**Comment by pineapplemachine** [comment] 2016-09-23 15:18
Have you attempted to compile the library again since you posted? I am currently able to compile the root `package.d` without errors, and with all tests passing. I'll be closing the issue in the absence of further failed attempts at compilation.

**Closed as completed** 2016-10-06 19:59 UTC
